version: '3'

services:
    brevets:
        build: brevets/.
        command: python -u flask_brevets.py
        ports:
            - "5000:5000"
        depends_on:
            - mongodb
        environment:
            MONGODB_HOSTNAME: mongodb
    mongodb:
        image: mongo:latest
        ports:
            - "5001:27017"